name:                zadanie2
version:             0.1.0.0
github:              karol50709/Haskell
license:             BSD3
author:              Karol O 
maintainer:          karol50709@gmail.com
copyright:           2017 

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            SQRT from 3 degree FastFib FastFibCount Square
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/karol50709/Haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  zadanie2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zadanie2

tests:
  zadanie2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zadanie2
